export const icons = {
   arrowBack: '/react-app-07/src/img/icons/arrowBack.svg',
   arrowDown: '/react-app-07/src/img/icons/arrowDown.svg',
   close: '/react-app-07/src/img/icons/close.png',
   comment_alert: '/react-app-07/src/img/icons/comment_alert.svg',
   comment: '/react-app-07/src/img/icons/comment.svg',
   crop_original: '/react-app-07/src/img/icons/crop_original.svg',
   edit_photo: '/react-app-07/src/img/icons/edit photo.svg',
   facebook_logo: '/react-app-07/src/img/icons/facebook_logo.svg',
   facebook_logo2: '/react-app-07/src/img/icons/facebook_logo2.svg',
   gmail_logo:'/react-app-07/src/img/icons/gmail_logo.svg',
   logo: '/react-app-07/src/img/icons/logo.svg',
   logoSingle: '/react-app-07/src/img/icons/logoSingle.svg',
   marker: '/react-app-07/src/img/icons/marker.svg',
   ok: '/react-app-07/src/img/icons/ok.svg',
   phone_call: '/react-app-07/src/img/icons/phone-call.svg',
   pin: '/react-app-07/src/img/icons/pin.svg',
   plus: '/react-app-07/src/img/icons/plus.svg',
   properties: '/react-app-07/src/img/icons/properties.svg',
   ruble_sign: '/react-app-07/src/img/icons/ruble_sign.svg',
   search: '/react-app-07/src/img/icons/search.svg',
   star_half: '/react-app-07/src/img/icons/star_half.svg',
   star: '/react-app-07/src/img/icons/star.svg',
   twitter_logo: '/react-app-07/src/img/icons/twitter_logo.svg',
   vk_logo: '/react-app-07/src/img/icons/vk_logo.svg',
   youtube_logo: '/react-app-07/src/img/icons/youtube_logo.svg'
};

export const category_icons = {
   armchair: '/react-app-07/src/img/category_icons/armchair.svg',
   backpack: '/react-app-07/src/img/category_icons/backpack.svg',
   calendar: '/react-app-07/src/img/category_icons/calendar.svg',
   camera: '/react-app-07/src/img/category_icons/camera.svg',
   car: '/react-app-07/src/img/category_icons/car.svg',
   Category: '/react-app-07/src/img/category_icons/Category.svg',
   DueDate0: '/react-app-07/src/img/category_icons/DueDate0.svg',
   DueDate1: '/react-app-07/src/img/category_icons/DueDate1.svg',
   excalamation_mark: '/react-app-07/src/img/category_icons/excalamation_mark.svg',
   headphones: '/react-app-07/src/img/category_icons/headphones.svg',
   hobby: '/react-app-07/src/img/category_icons/hobby.svg',
   imac: '/react-app-07/src/img/category_icons/imac.svg',
   magician: '/react-app-07/src/img/category_icons/magician.svg',
   microwave: '/react-app-07/src/img/category_icons/microwave.svg',
   Parameters0: '/react-app-07/src/img/category_icons/Parameters0.svg',
   Parameters1: '/react-app-07/src/img/category_icons/Parameters1.svg'
}